# Generated by Django 4.2.1 on 2023-05-07 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_photo_1_alter_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='area_in_marla',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
    ]
