# Generated by Django 4.2.1 on 2023-05-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0007_alter_listing_bathrooms_alter_listing_photo_1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="is_published",
            new_name="nearMarket",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="bathrooms",
        ),
        migrations.AddField(
            model_name="listing",
            name="nearMasjid",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="city",
            field=models.CharField(max_length=15),
        ),
    ]
