# Generated by Django 4.2.1 on 2023-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0008_rename_is_published_listing_nearmarket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bathrooms",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
